# Generated by Django 4.1.3 on 2022-11-13 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=200)),
                ('context_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BoolOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonlogic_operator', models.CharField(choices=[('==', 'equals'), ('!=', 'does not equal'), ('>', 'greater than'), ('>=', 'greater than or equal to'), ('<', 'less than'), ('<=', 'less than or equal to'), ('in', 'in (substring or subset of)')], max_length=2)),
                ('context_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_name', models.CharField(max_length=200)),
                ('is_free_text', models.BooleanField(default=False)),
                ('context_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logic_string', models.CharField(max_length=200)),
                ('jsonlogic_only_boolean_symbols', models.JSONField(blank=True)),
                ('jsonlogic_full_conditions', models.JSONField(blank=True)),
                ('num_conditions', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RuleActionPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonlogic_if_statement', models.JSONField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.action')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_index', models.PositiveIntegerField()),
                ('freetext_subject', models.CharField(blank=True, max_length=200)),
                ('freetext_object', models.CharField(blank=True, max_length=200)),
                ('jsonlogic_condition', models.JSONField()),
                ('operand_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rules.property')),
                ('operand_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rules.property')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.booloperator')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule')),
            ],
        ),
    ]
